name: CI

# Trigger workflow on pull requests to `main`
on:
  # Uncomment below if CI should run on direct pushes to `main`
  # push:
  #   branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust toolchain if missing (typically not needed on ubuntu-latest)
      - name: Ensure Rust is available
        run: |
          if ! command -v cargo &> /dev/null; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      # Cache Solana tools directory
      - name: Cache Solana tools
        uses: actions/cache@v4
        with:
          path: ~/.local/share/solana
          key: ${{ runner.os }}-solana-anza-v1

      # Install Solana CLI and cargo-build-sbf if not cached
      - name: Install Solana tools (cargo-build-sbf)
        run: |
          if [ ! -f "$HOME/.local/share/solana/install/active_release/bin/cargo-build-sbf" ]; then
            sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          fi
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      # Cache Rust crates and build artifacts
      - name: Cache cargo registry and target artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Run this only if using a cargo workspace
      # Build all Rust crates (adjust if not using a workspace)
      - name: Build Rust project
        run: cargo build --verbose

      # Build Solana program using cargo-build-sbf
      - name: Build Solana SBF program
        run: cargo build-sbf --manifest-path=program/Cargo.toml --verbose

      # Run all tests (unit, integration, etc)
      - name: Run tests
        run: cargo test --verbose

      # Run Clippy for linting
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      # Run rustfmt to check formatting
      - name: Run fmt
        run: cargo fmt --all -- --check
